version: '3'

networks:
  neo4j_net:

services:

  neo4j:
    hostname: neo4jdb
    image: neo4j:4.2-enterprise
    networks:
      - neo4j_net
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/changeme
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes

  generator:
    build: .
    networks:
      - neo4j_net
    depends_on:
      - neo4j
    command: 5 10000 100
    environment:
      - NEO4J_URI=neo4j://neo4jdb:7687
      - NEO4j_PASSWORD=changeme
